version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./data:/app/data
    environment:
      - SECRET_KEY=your-secret-key-change-in-production
      - FLASK_ENV=production
    restart: unless-stopped

volumes:
  data: