"""Add game history and off request models

Revision ID: 1e54a98554e7
Revises: 
Create Date: 2025-07-09 14:49:29.978697

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e54a98554e7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('kim_bai_used')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('kim_bai_used', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
