"""add theme to user

Revision ID: 659e038416ef
Revises: fdfff228cb46
Create Date: 2025-07-11 15:45:43.768045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '659e038416ef'
down_revision = 'fdfff228cb46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
