"""Add notes and tags to GameHistory

Revision ID: fdfff228cb46
Revises: 1e54a98554e7
Create Date: 2025-07-11 08:36:10.261686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdfff228cb46'
down_revision = '1e54a98554e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_history', schema=None) as batch_op:
        batch_op.drop_column('tags')
        batch_op.drop_column('notes')

    # ### end Alembic commands ###
